### ISSUE TITLE
qualpalr archived on CRAN

### ISSUE THREAD

**Issue by stitam** [jolars/qualpalr#6]
Hi, I've just noticed that qualpalr has been archived on CRAN (https://cran.r-project.org/web/packages/qualpalr/index.html). I was wondering if you are planning to restore it soom or shall we use the github version instead? Many thanks.

**Comment by jolars** [comment]
Oh, hm, thanks for the heads-up. I wasn't aware it had even been archived. Apparently I've used a now outdated and defunct e-mail address. Yes, I very much plan to get it back on cran again. I'll try to contact the CRAN team and see if I can figure it out.

**Comment by jolars** [comment]
It's back! https://cran.r-project.org/package=qualpalr
